# This is a basic workflow to help you get started with Actions

name: Build & Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  push:
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    #- name: Login to ACR
    #  uses: azure/docker-login@v1
    #  with:
    #   login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
    #   username: ${{ secrets.REGISTRY_USERNAME }}
    #   password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: docker build and push 
      run: |
        docker build . --file Dockerfile --tag ahysing/lazychat:latest
        